//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 04:00:38 AM MDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://maven.apache.org/POM/4.0.0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package clojarsAnalizer.core.model.packageDescriptor.maven;
