//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0-M4 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.08 at 04:00:38 AM MDT 
//


package clojarsAnalizer.core.model.packageDescriptor.maven;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *         
 *         The &lt;code&gt;&amp;lt;scm&amp;gt;&lt;/code&gt; element contains informations required to the SCM
 *         (Source Control Management) of the project.
 *         
 *       
 * 
 * &lt;p&gt;Java class for Scm complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType name="Scm"&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;all&amp;gt;
 *         &amp;lt;element name="connection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="developerConnection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *         &amp;lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&amp;gt;
 *       &amp;lt;/all&amp;gt;
 *       &amp;lt;attribute name="child.scm.connection.inherit.append.path" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *       &amp;lt;attribute name="child.scm.developerConnection.inherit.append.path" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *       &amp;lt;attribute name="child.scm.url.inherit.append.path" type="{http://www.w3.org/2001/XMLSchema}string" /&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Scm", propOrder = {

})
public class Scm {

    protected String connection;
    protected String developerConnection;
    @XmlElement(defaultValue = "HEAD")
    protected String tag;
    protected String url;
    @XmlAttribute(name = "child.scm.connection.inherit.append.path")
    protected String childScmConnectionInheritAppendPath;
    @XmlAttribute(name = "child.scm.developerConnection.inherit.append.path")
    protected String childScmDeveloperConnectionInheritAppendPath;
    @XmlAttribute(name = "child.scm.url.inherit.append.path")
    protected String childScmUrlInheritAppendPath;

    /**
     * Gets the value of the connection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnection() {
        return connection;
    }

    /**
     * Sets the value of the connection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnection(String value) {
        this.connection = value;
    }

    /**
     * Gets the value of the developerConnection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeveloperConnection() {
        return developerConnection;
    }

    /**
     * Sets the value of the developerConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeveloperConnection(String value) {
        this.developerConnection = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the childScmConnectionInheritAppendPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildScmConnectionInheritAppendPath() {
        return childScmConnectionInheritAppendPath;
    }

    /**
     * Sets the value of the childScmConnectionInheritAppendPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildScmConnectionInheritAppendPath(String value) {
        this.childScmConnectionInheritAppendPath = value;
    }

    /**
     * Gets the value of the childScmDeveloperConnectionInheritAppendPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildScmDeveloperConnectionInheritAppendPath() {
        return childScmDeveloperConnectionInheritAppendPath;
    }

    /**
     * Sets the value of the childScmDeveloperConnectionInheritAppendPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildScmDeveloperConnectionInheritAppendPath(String value) {
        this.childScmDeveloperConnectionInheritAppendPath = value;
    }

    /**
     * Gets the value of the childScmUrlInheritAppendPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildScmUrlInheritAppendPath() {
        return childScmUrlInheritAppendPath;
    }

    /**
     * Sets the value of the childScmUrlInheritAppendPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildScmUrlInheritAppendPath(String value) {
        this.childScmUrlInheritAppendPath = value;
    }

}
